const projects = [
  {
    name: 'Carte Blanche',
    slug: 'carte-blanche',
    id: '1',
    type: 'graphic',
    year: '2013',
    tags: ['Poster'],
    horizontal: false,
    mp4: false,
    image: '/CartaBlanche/4.JPG',
    img1: '/CartaBlanche/1.jpg',
    sources: [
      {
        type: 'img',
        img: '/CartaBlanche/5.JPG',
        rows: 4,
        cols: 2,
      },
      {
        type: 'img',
        img: '/CartaBlanche/4.JPG',
        rows: 4,
        cols: 2,
      },
      {
        type: 'img',
        img: '/CartaBlanche/2.JPG',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/CartaBlanche/3.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/CartaBlanche/6.JPG',
        rows: 2,
        cols: 2,
      },
    ],
    attributes: {
      description:
        'I had the honor of being invited by Form magazine to design a poster for their "Carte Blanche" limited edition poster series, for their May/June 2013 issue, in collaboration with the Berlin furniture design Studio Hausen.',
    },
  },
  {
    name: 'Circ',
    slug: 'circ',
    id: '2',
    type: 'typeface',
    year: '2011',
    tags: null,
    horizontal: true,
    mp4: false,
    image: '/CoverPhotos/Galleries/CircH.jpg',
    sources: [
      {
        type: 'img',
        img: '/Circ/2.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Circ/3.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Circ/7.JPG',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Circ/5.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Circ/6.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Circ/4.JPG',
        rows: 4,
        cols: 4,
      },
    ],
    attributes: {
      description:
        'Circ is a modular display font, based on geometric forms deriving from the circle.',
    },
  },
  {
    name: 'DinMachine',
    slug: 'din-machine',
    id: '3',
    type: 'graphic',
    year: '2014',
    tags: ['Poster', 'Visual-Identity', 'Packaging'],
    horizontal: true,
    mp4: false,
    landing: '/CoverPhotos/Lading/DinMachine.jpg',
    image: '/CoverPhotos/Galleries/DinMachine.jpg',
    sources: [
      {
        type: 'img',
        img: '/DinMachine/2.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/DinMachine/3.jpg',
        rows: 2,
        cols: 3,
      },
      {
        type: 'img',
        img: '/DinMachine/6.jpg',
        rows: 2,
        cols: 1,
      },
      {
        type: 'img',
        img: '/DinMachine/7.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/DinMachine/4.jpg',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/DinMachine/8.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/DinMachine/9.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/DinMachine/12.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/DinMachine/11.jpg',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/DinMachine/10.jpg',
        rows: 1,
        cols: 4,
      },
      {
        type: 'img',
        img: '/DinMachine/17.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/DinMachine/18.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/DinMachine/20.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/DinMachine/13.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/DinMachine/14.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/DinMachine/15.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/DinMachine/16.jpg',
        rows: 2,
        cols: 4,
      },

      {
        type: 'img',
        img: '/DinMachine/19.jpg',
        rows: 2,
        cols: 4,
      },

      {
        type: 'img',
        img: '/DinMachine/21.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/DinMachine/24.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/DinMachine/25.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/DinMachine/23.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/DinMachine/26.jpg',
        rows: 2,
        cols: 2,
      },
    ],
    attributes: {
      description:
        'The New York based electronic experimental rock band DinMachine, hired me to develop the Logo & CD cover design for their first album Dance to Reason. I also designed a t-shirt for the CD launching. DinMachine is a collaboration between Nisi Jacobs and Michael J. Schumacher. They have been making music together since 2009 and have performed at renown places, such as MoMA New York. Ken Jacobs (a world renowned experimental filmmaker) has used both Schumacher’s and DinMachine’s music for his published films. When asking Nisi and Michael about themselves, the band and the music they create together, they came up with some information that I found very interesting to work with: “We want to grab people with the music, get them moving”. “DinMachine’s music has been generally described as non-classifiable”. “Our music, we feel, has elements that are very engaging and involving, and others that need distance and detachment”. “We like the idea of hot vs cold, engaging sexiness”. For the logo, I decided to work with the concept of “non-classifiable” as well as the idea of contrast/opposite. I made an experimental logo, mixing capital and lower cases letters in order to create something that defies classification. The letters are all cut differently which adds movement and vibration to the logo which echoes the music they produce. As for the CD cover, I played with the idea of sexiness, opposition (cold vs hot, engage/detach) and movement.',
    },
  },
  {
    name: 'Exentra',
    slug: 'exentra',
    id: '4',
    type: 'typeface',
    year: '2015',
    tags: ['Editorial'],
    horizontal: false,
    mp4: false,
    landing: '/CoverPhotos/Lading/Exentra.jpg',
    image: '/CoverPhotos/Galleries/ExentraV.jpg',
    img1: '/Exentra/1.jpg',
    sources: [
      {
        type: 'img',
        img: '/Exentra/3.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Exentra/2.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Exentra/4.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Exentra/5.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Exentra/6.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Exentra/7.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Exentra/12.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Exentra/13.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Exentra/25.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Exentra/27.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Exentra/15.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Exentra/16.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Exentra/17.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Exentra/19.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Exentra/8.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Exentra/32.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Exentra/21.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Exentra/20.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Exentra/18.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Exentra/29.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Exentra/26.jpg',
        rows: 2,
        cols: 3,
      },
      {
        type: 'img',
        img: '/Exentra/24.jpg',
        rows: 2,
        cols: 1,
      },
      {
        type: 'img',
        img: '/Exentra/31.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Exentra/11.jpg',
        rows: 2,
        cols: 1,
      },
      {
        type: 'img',
        img: '/Exentra/22.jpg',
        rows: 2,
        cols: 3,
      },
      {
        type: 'img',
        img: '/Exentra/14.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Exentra/23.jpg',
        rows: 2,
        cols: 2,
      },

      {
        type: 'img',
        img: '/Exentra/30.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Exentra/10.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Exentra/9.jpg',
        rows: 2,
        cols: 2,
      },
    ],
    attributes: {
      description:
        'Exentra is the project I developed during the MATD (Masters in Typeface Design) course 2014–15 at the University of Reading. My intention was to design an innovative and unique typeface that would appeal to designers doing forward-looking designs. Therefore, this typeface family was conceived for publications promoting forward-thinking through a contemporary and experimental vision of modern culture and trends. Its style combines the elegance and warmth of calligraphy with the precision and digital sharpness of the computer process that give it a contemporary look. Unconventional letter shapes, and the playful and dynamic design reinforce the idiosyncrasy of the typeface.',
    },
  },
  {
    name: 'Feria Del Libro',
    slug: 'feria-del-libro',
    id: '5',
    type: 'graphic',
    year: '2018',
    tags: ['Poster'],

    horizontal: false,
    mp4: false,
    landing: '/CoverPhotos/Lading/FeriaDelLibro.jpg',
    image: '/CoverPhotos/Galleries/FeriaDelLibro.jpg',
    img1: '/FeriaDelLibro/1.jpg',
    sources: [
      {
        type: 'img',
        img: '/FeriaDelLibro/3.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FeriaDelLibro/4.jpg',
        rows: 2,
        cols: 2,
      },
      { type: 'img', img: '/FeriaDelLibro/2.jpg', rows: 2, cols: 4 },
    ],
    attributes: {
      description:
        'Proposition I made for the poster competition for the "18th Book Fair for children and young people" in Uruguay - which I did not win. My intention was to create an image that would show books in a playful and intriguing manner, that would appeal to kids\'/ curiosity and encourage them to go explore the discoveries opportunities a book faire offers. More generally, I wanted kid to perceive a book faire as an exciting place to visit. My mottos were: Knowledge is freedom. Reading is fun.',
    },
  },
  {
    name: 'Fédération Genevoise de Coopération',
    slug: 'federation-genevoise-de-cooperation',
    id: '6',
    type: 'graphic',
    year: '2012',
    tags: ['Visual-Identity', 'Illustration'],
    horizontal: false,
    mp4: false,
    landing: '/CoverPhotos/Lading/FGC.jpg',
    image: '/FGC/7.gif',
    img1: '/FGC/FGC.jpg',
    sources: [
      {
        type: 'img',
        img: '/FGC/19.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/1.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/2.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/FGC/3.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/4.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/5.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/6.gif',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/7.gif',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/8.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/9.gif',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/10.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/31.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/32.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/18.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/FGC/12.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/13.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/14.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/FGC/15.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/16.JPG',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/17.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/20.jpg',
        rows: 1,
        cols: 4,
      },
      {
        type: 'img',
        img: '/FGC/23.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/22.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/24.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/25.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/21.jpg',
        rows: 2,
        cols: 4,
      },

      {
        type: 'img',
        img: '/FGC/26.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/27.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/28.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/30.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FGC/29.jpg',
        rows: 2,
        cols: 4,
      },
    ],
    attributes: {
      description:
        'Re-branding of Fédération Genevoise de Coopération (FGC). The Fédération Genevoise de Coopération reassembles about fifty associations with headquarters in Geneva. The aim behind it is to aid developing countries and raise public awareness by financing and mentoring projects helping to battle inequality and provide freedom of choice to these communities.',
    },
  },
  {
    name: 'Flag Of Peace',
    slug: 'flag-of-peace',
    id: '7',
    type: 'graphic',
    year: '2017',
    tags: null,
    horizontal: true,
    mp4: false,
    landing: '/CoverPhotos/Lading/FlagOfPeace.jpg',
    image: '/CoverPhotos/Galleries/FlagOfPeace.jpg',
    sources: [
      {
        type: 'img',
        img: '/FlagOfPeace/2.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/FlagOfPeace/3.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FlagOfPeace/4.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FlagOfPeace/6.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FlagOfPeace/8.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FlagOfPeace/7.jpg',
        rows: 2,
        cols: 4,
      },
    ],
    attributes: {
      description:
        'Flags of Peace (NL) honoured me with an invitation to design an international peace flag to represent my country (Uruguay) in their international exhibition “Flags of Peace” which travels around the world. Many bold designers and studios have already joined the great cause behind this project by designing the flag for their respective countries. I believe that for a flag to be International it has to represent/address all cultures equally. Therefore, we cannot rely on words, since language only represents a certain culture. Although there are some symbols that are internationally associated with peace, when looking at their origins research showed me that, for the most part, they either originally represented something else or were linked to a specific religion. Accordingly, the use of them was judged inappropriate. I observed that there are normally two sides in a conflict putting peace away, where either two persons or groups (nations, towns, etc.) are confronted for things such as religion, genre, skin color, social class, origins, and so on. For peace to take place, these two sides need to come to terms and see each other as equals in order to impart mutual respect. My flag carries a message of hope, showing these opposite sides finding common ground, complementing each other and sharing, instead of dividing or excluding. Symmetry was used as a means of representing equality and balance between two sides that despite looking different (color), they are equals (surface and shape). The symmetrical image is also an analogy for a mirror, encouraging people to find a piece of themselves in the one in front of us.',
    },
  },
  {
    name: 'Freedom Of Movement',
    slug: 'freedom-of-movement',
    id: '8',
    type: 'graphic',
    year: '2017',
    tags: ['Poster'],
    horizontal: false,
    mp4: false,
    image: '/CoverPhotos/Galleries/FreedomOfMovement.jpg',
    img1: '/FreedomOfMovement/2.jpg',
    sources: [
      { type: 'img', img: '/FreedomOfMovement/1.jpg', rows: 2, cols: 4 },
      {
        type: 'img',
        img: '/FreedomOfMovement/3.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/FreedomOfMovement/4.jpg',
        rows: 2,
        cols: 2,
      },
    ],
    attributes: {
      description:
        "The poster reflects on the position that USA has recently adopted with regards to foreign citizens. The jenga (board game) is an analogy for USA’s society from which the president is picking up people after their origins/nationality to decide whether they belong in or out its territory, with no regard for the impact these actions could have on those peoples’ lives as well as on USA's own society. The jenga echoes the increasing tension, weakening and instability taking place in USA's society, since each ‘move' represents (through cultural impoverishment, international friction and the possibility of retaliation that comes with it, among other things) a higher risk of collapse.",
    },
  },
  {
    name: 'Geneva Motor Show',
    slug: 'geneva-motor-show',
    id: '9',
    type: 'graphic',
    year: '2014',
    tags: ['Visual-Identity', 'Animation', 'Packaging'],
    horizontal: true,
    mp4: false,
    landing: '/CoverPhotos/Lading/GenevaMotorShow.jpg',
    image: '/GenevaMotorShow/19.jpg',
    sources: [
      {
        type: 'img',
        img: '/GenevaMotorShow/1.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/2.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/3.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/4.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/8.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/9.jpg',
        rows: 2,
        cols: 1,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/10.jpg',
        rows: 2,
        cols: 3,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/11.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/13.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/12.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/15.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/16.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/17.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/14.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/20.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/22.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/24.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/23.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'video',
        url: '/GenevaMotorShow/MotorShowVideo.mp4',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/25copy.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/7.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/6.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/5.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/26.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GenevaMotorShow/18.jpg',
        rows: 2,
        cols: 4,
      },
    ],
    attributes: {
      description:
        "This visual identity was used in all of the different national and international communication campaigns for the Geneva International Motor Show 2014. I wanted to propose a design concept that really deferred from the “regular” style of the Geneva Motor Show which typically consisted of busy images including figurative automobile representations. Furthermore, I also noticed that text and image were treated as two completely distinct elements lacking integration. The text ended up taking the shape of a rigid block that was placed the same way across all supports. My goal was then to create a minimal and abstract design that evokes feelings and emotions related to the automobile sector rather than focusing on the actual car itself. Additionally, I wanted to make the text the protagonist element of my design. Thus, I proposed a design with different reading levels, where the lines suggest a network of roads which evoke the number of visitors coming to visit the Motor Show every year from around all over the world. They also suggest the shape of the most iconic landmarks composing the traditional Genevan landscape: Cars, mountains, the Jet D'eau, and so on. As for the colours, I was inspired by the season in which the Geneva Motor Show takes place, spring. The creation and composition of the poster is entirely drawn out typographically.",
    },
  },
  {
    name: 'Genève Typeface',
    slug: 'geneve-typeface',
    id: '10',
    type: 'typeface',
    year: '2014',
    tags: ['Editorial', 'Poster'],
    horizontal: true,
    mp4: false,
    landing: '/CoverPhotos/Lading/GeneveTypeface.jpg',
    image: '/GeneveTypeface/36.jpg',
    sources: [
      {
        type: 'img',
        img: '/GeneveTypeface/1.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/3.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/2.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/16.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/8.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/9.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/10.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/11.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/20.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/24.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/25.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/26.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/27.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/28.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/29.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/32.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/31.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/30.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/33.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/34.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/37.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/38.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/39.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/41.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/42.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/43.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/59b.jpg',
        rows: 2,
        cols: 1,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/44.JPG',
        rows: 2,
        cols: 3,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/22.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/23.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/45.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/46.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/48.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/49.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/50.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/51.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/52.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/53.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/54.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/55.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/57.jpg',
        rows: 2,
        cols: 3,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/58.jpg',
        rows: 2,
        cols: 1,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/60.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/61.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/62.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/64.jpg',
        rows: 2,
        cols: 1,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/65.jpg',
        rows: 2,
        cols: 3,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/66.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/68.jpg',
        rows: 2,
        cols: 1,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/69.jpg',
        rows: 2,
        cols: 3,
      },
      {
        type: 'img',
        img: '/GeneveTypeface/67.jpg',
        rows: 2,
        cols: 4,
      },
    ],
    attributes: {
      description:
        'Genève is a type family inspired by the rich typographic history of Geneva and was conceived as part of my Bachelor thesis at HEAD University, Geneva. In developing Genève I was inspired by the typeface used by French printer/editor/publisher Henri II Estienne in his famous book Thesaurus Linguæ Græcæ, published in Geneva in 1572. This typeface was brought to Geneva by Henri’s father, Robert Estienne, who, before settling in Geneva and working as Calvin’s printer, was the printer of France’s King, François I. This typeface highly influenced the typographers and printers in Geneva at that time. Henri and Robert Estienne’s work in Geneva helped it to become one of the most important cities in Europe for print and typography in the sixteenth century. Designed to be used on any type of printed support, Genève is a typography with personality and flexibility, which allows designers to express their ideas in different ways without losing coherence. Genève consists of four styles: Classique (Humanist serif), Austère (Geometric serif), Spontanée (Humanist sans-serif) and Alternative (Stencil, display version). These styles correspond to the different profiles of the city, reflecting its multiculturalism and diversity. I received the BEA Fondation Award for Young Artists for my work on the Genève Typeface. Some years later Genève typeface was further developed and became Thesaurus.Credits: Binding and photos of “Genève: The making of”: Aniello Frasca',
    },
  },
  {
    name: 'Goes Around',
    slug: 'goes-around',
    id: '11',
    type: 'graphic',
    year: '2014',
    tags: ['Poster'],
    horizontal: false,
    mp4: false,
    image: '/GoesAround/1.jpg',
    img1: '/GoesAround/5.jpg',
    sources: [
      {
        type: 'img',
        img: '/GoesAround/4.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GoesAround/1.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/GoesAround/2.jpg',
        rows: 1,
        cols: 2,
      },
    ],
    attributes: {
      description:
        'For a school project in collaboration with the RATP (Parisian autonomous transport society), we were asked to create a 10 second long animation to wish the passengers a happy new year 2014. The animations were shown on the large HD screens at the Franklin Roosevelt and Europe metro stops in Paris, France, from December 24, 2013 to January 8, 2014. My intention was to confront themselves, that they reflect on who they are and how they behave with others. I found this most interesting and thought that I could respond to this in various ways. Therefore I decided to also create two posters: one derived from the animation and the other, completely independent - Both with no intention of being shown on the RATP -. For the independent poster �2014 goes around...comes around� (see above), I handled the subject in a more explicit and trashy way.',
    },
  },
  {
    name: 'Its Up To You',
    slug: 'its-up-to-you',
    id: '12',
    type: 'graphic',
    year: '2014',
    tags: ['Animation', 'Poster'],
    horizontal: true,
    mp4: false,
    landing: '/CoverPhotos/Lading/ItsUpToYou.jpg',
    image: '/ItsUpToYou/5.JPG',
    sources: [
      {
        type: 'img',
        img: '/ItsUpToYou/8.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/ItsUpToYou/14.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/ItsUpToYou/13.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/ItsUpToYou/1.JPG',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/ItsUpToYou/6.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/ItsUpToYou/2.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/ItsUpToYou/11.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/ItsUpToYou/10.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/ItsUpToYou/12.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/ItsUpToYou/3.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/ItsUpToYou/15.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'video',
        url: '/ItsUpToYou/Animation.mp4',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/ItsUpToYou/9.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/ItsUpToYou/4.jpg',
        rows: 2,
        cols: 4,
      },
    ],
    attributes: {
      description:
        'For a school project at HEAD - Geneva, in collaboration with the RATP (Parisian autonomous transport society), we were invited to create a 10 second long animation to wish the passengers a happy new year 2014. The animations were shown on the large HD screens at the Franklin Roosevelt and Europe metro stops in Paris, France. My intention was to confront the public with themselves and make them reflect on who they are and how they behave with others. I thought that I could address this premise in various ways. Thus, I decided to also create two posters: one derived from the animation and the other completely independent . For "2014 it\'s up to you" (poster based on the animation), I handled the subject in a more subtle, abstract and, somehow, poetic way. I inserted a small text in the center of the mirror so that people would have to get closer to the poster in order to read the text «it\'s up to you» and, at the same time they discover the text they would see themselves  reflected in the mirror from a really close range enhancing the effect of confrontation. Poster: 50x70cm / Screen printing: black and white on mirror paper / 20 copies You can find the other poster “2014 goes around… comes around” here.',
    },
  },
  {
    name: 'Jeu De Regards',
    slug: 'jeu-de-regards',
    id: '13',
    type: 'graphic',
    year: '2012',
    tags: ['Poster'],
    horizontal: true,
    mp4: false,
    landing: '/CoverPhotos/Lading/JoieDeLire.jpg',
    image: '/CoverPhotos/Galleries/JoieDeLire.jpg',
    sources: [
      {
        type: 'img',
        img: '/JoieDeLire/2.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/JoieDeLire/4.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/JoieDeLire/5.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/JoieDeLire/3.JPG',
        rows: 2,
        cols: 2,
      },
    ],
    attributes: {
      description:
        "'Jeu de regards': Poster design for the exhibition commemorating the 25th anniversary of Geneva'/s own publishing house, La Joie de Lire, which took place at the 26 me Salon International du livre et de la presse, in Geneva.",
    },
  },
  {
    name: 'Letter Stamps',
    slug: 'letter-stamps',
    id: '14',
    type: 'typeface',
    year: '2013',
    tags: ['Poster'],
    horizontal: true,
    mp4: false,
    image: '/CoverPhotos/Galleries/LetterStamps.jpg',
    sources: [
      {
        type: 'img',
        img: '/LetterStamps/1.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/LetterStamps/2.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LetterStamps/3.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LetterStamps/4.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/LetterStamps/24.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/LetterStamps/6.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LetterStamps/5.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LetterStamps/7.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LetterStamps/8.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LetterStamps/9.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LetterStamps/10.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/LetterStamps/13.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LetterStamps/15.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LetterStamps/14.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/LetterStamps/12.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LetterStamps/23.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LetterStamps/11.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/LetterStamps/22.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/LetterStamps/20.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LetterStamps/21.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LetterStamps/16.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LetterStamps/18.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LetterStamps/19.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LetterStamps/17.JPG',
        rows: 2,
        cols: 2,
      },
    ],
    attributes: {
      description:
        'For a school project we were asked to make typographic stamps in order to create an alphabet and then design posters with it. The challenge I set myself was to create a stamp that would stand out for its versatility and simplicity. I decided to use rope as the stamp material. For this, I designed a matrix which would work both as a support for the rope as well as a grid for the typeface. My matrix allows for the composition of all the glyphs of the alphabet and 4 different weights (light, regular, medium and bold).',
    },
  },
  {
    name: 'Make A Whish',
    slug: 'make-a-whish',
    id: '15',
    type: 'graphic',
    year: '2018',
    tags: ['Poster'],
    horizontal: false,
    mp4: false,
    landing: '/CoverPhotos/Lading/MakeAWish.jpg',
    image: '/CoverPhotos/Galleries/MakeAwish.jpg',
    img1: '/MakeAWhish/1.jpg',
    sources: [
      {
        type: 'img',
        img: '/MakeAWhish/3.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/MakeAWhish/2.jpg',
        rows: 2,
        cols: 2,
      },
    ],
    attributes: {
      description:
        'In many cultures around the world a shooting star is associated with dreams and hope, as it is believed that this phenomenon (a shooting star) has the magical power of granting us a wish. Furthermore, a shooting star is a very ephemeral thing, which echoes the idea of life itself. I wanted to play with this concept on my 2018 greeting poster. Thus, I created a sky full of shooting stars, where the main ones are suggesting the numbers 2, 0, 1, 8. The result is a 2018 made out of opportunities, hopes and magic, that has to be fully exploited before vanishing forever. The poster becomes an invitation to dream and reflect on what we would wish happen this new year if we were granted a wish.',
    },
  },
  {
    name: 'Manifesta',
    slug: 'manifesta',
    id: '16',
    type: 'typeface',
    year: '2012',
    tags: ['Poster'],
    horizontal: false,
    mp4: false,
    landing: '/CoverPhotos/Lading/Manifesta.jpg',
    image: '/Manifesta/13.gif',
    img1: '/Manifesta/5.jpg',
    sources: [
      {
        type: 'img',
        img: '/Manifesta/2.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Manifesta/7.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Manifesta/13.gif',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Manifesta/6.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Manifesta/16.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Manifesta/19.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Manifesta/18.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Manifesta/15.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Manifesta/4.JPG',
        rows: 2,
        cols: 1,
      },
      {
        type: 'img',
        img: '/Manifesta/3.jpg',
        rows: 2,
        cols: 3,
      },
      {
        type: 'img',
        img: '/Manifesta/11.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Manifesta/14.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Manifesta/9.jpg',
      },
      {
        type: 'img',
        img: '/Manifesta/17.jpg',
      },
      {
        type: 'img',
        img: '/Manifesta/12.jpg',
      },

      {
        type: 'img',
        img: '/Manifesta/10.jpg',
      },
    ],
    attributes: {
      description:
        'Title or short-text font, influenced both by the geometry-favoring artistic movements of the beginning of the 20th Century and the work of Dutch designer Max Kisman. This typeface aims to explore the relationship between the different parts of the letterforms as well as their hierarchy, while teasing with the limits of legibility. Manifesta family is formed by four different weights (light, regular, medium, bold), each one with uppercase and lowercase letters, numbers, punctuation marks and diacritic characters. ',
    },
  },
  {
    name: 'Mi Mujer',
    slug: 'mi-mujer',
    id: '17',
    type: 'graphic',
    year: '2013',
    tags: ['Poster'],
    horizontal: false,
    mp4: false,
    landing: '/CoverPhotos/Lading/MiMujer.jpg',
    image: '/CoverPhotos/Galleries/MiMujer.jpg',
    img1: '/MiMujer/1.jpg',
    sources: [
      {
        type: 'img',
        img: '/MiMujer/2.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/MiMujer/3.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/MiMujer/4.jpg',
        rows: 2,
        cols: 4,
      },
    ],
    attributes: {
      description:
        "Poster design inspired by Nicolas Jaar's song Mi MujerSchool Project.",
    },
  },
  {
    name: 'New Year, New Fight',
    slug: 'new-year-new-fight',
    id: '18',
    type: 'graphic',
    year: '2015',
    tags: ['Poster'],
    horizontal: false,
    mp4: false,
    landing: '/CoverPhotos/Lading/NewYearNewFight.jpg',
    image: '/CoverPhotos/Galleries/NewYearNewFight.jpg',
    img1: '/NewYearNewFight/1.jpg',
    sources: [
      {
        type: 'img',
        img: '/NewYearNewFight/3.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/NewYearNewFight/2.jpg',
        rows: 2,
        cols: 2,
      },

      {
        type: 'img',
        img: '/NewYearNewFight/4.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/NewYearNewFight/5.jpg',
        rows: 1,
        cols: 2,
      },
    ],
    attributes: {
      description:
        'I designed this poster at the end of 2014, just to share my thoughts about the new year 2015, which I knew was going to be a particularly tough one for me. This poster obtained an Honorary Mention at Trnava Poster Triennial International competition 2015.',
    },
  },
  {
    name: 'Paléo',
    slug: 'paleo',
    id: '19',
    type: 'graphic',
    year: '2013',
    tags: ['Visual-Identity', 'Poster'],
    horizontal: false,
    mp4: false,
    landing: '/CoverPhotos/Lading/Paleo.jpg',
    image: '/CoverPhotos/Galleries/Paleo.jpg',
    img1: '/Paleo/1.jpg',
    sources: [
      {
        type: 'img',
        img: '/Paleo/2.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Paleo/3.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Paleo/5.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Paleo/4.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Paleo/Paleo.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Paleo/6.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Paleo/BoiteDefinitive-02c.jpg',
        rows: 2,
        cols: 4,
      },
    ],
    attributes: {
      description:
        'Second prize at the Paléo Festival Nyon Poster and Identity contest (Poster + merchandising). Paléo Festival is today one of Europe’s most important musical events.',
    },
  },
  {
    name: 'Point de Fuite',
    slug: 'point-de-fuite',
    id: '20',
    type: 'graphic',
    year: '2012',
    tags: ['Visual-Identity'],
    horizontal: true,
    mp4: false,
    image: '/CoverPhotos/Galleries/PointDeFuite.jpg',
    soruces: [
      {
        type: 'img',
        img: '/Point/1.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/2.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/4.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/5.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/6.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/7.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/8.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/9.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/25.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Point/10.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/11.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/12.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/13.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/14.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/15.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/16.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/17.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/18.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/19.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/20.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/24.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Point/22.jpg',
        rows: 2,
        cols: 2,
      },

      {
        type: 'img',
        img: '/Point/21.jpg',
        rows: 2,
        cols: 2,
      },
    ],
    attributes: {
      description:
        "Conception and mounting of the exhibition '/Point de Fuite'/, which presented artist Isabelle Pralong'/s career retrospective and took place in Geneva'/s Biblioth�que de la Cit� from Dec 9th, 2011 to Jan 31st, 2012. Done in collaboration with Tammara Leites, Alexia Segura, Pierre Schilling et Antoine Schmitt, as an assignment for Sandrine Pelletier'/s scenography course at HEAD - Geneve.",
    },
  },
  {
    name: 'The Lady from The Sea',
    slug: 'the-lady-from-the-sea',
    id: '21',
    type: 'graphic',
    year: '2014',
    tags: ['Photography'],
    horizontal: true,
    mp4: false,
    landing: '/CoverPhotos/Lading/DameDeLaMer.jpg',
    image: '/CoverPhotos/Galleries/LaDameDeLaMere.jpg',
    sources: [
      {
        type: 'img',
        img: '/LaDamedeLaMer/1.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/LaDamedeLaMer/2.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/LaDamedeLaMer/3.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/LaDamedeLaMer/7.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LaDamedeLaMer/6.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LaDamedeLaMer/5.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LaDamedeLaMer/8.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/LaDamedeLaMer/4.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/LaDamedeLaMer/10.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/LaDamedeLaMer/12.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LaDamedeLaMer/13.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LaDamedeLaMer/11.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/LaDamedeLaMer/14.JPG',
        rows: 2,
        cols: 2,
      },
    ],
    attributes: {
      description:
        'For an University project, in collaboration with the Carouge Theatre (Geneva), we were asked to reinterpret the play ”The lady from the sea” written by Henrik Ibsen through a series of photographs. My work deals with an everyday life overtaken by fear and anguish provoked by ghosts of a past love. Past and present blend together, memories and reality collide and dreams become real. The photos were exhibited at the Fusterie exhibition space – Geneva.',
    },
  },
  {
    name: 'Post Tenebras Rock',
    slug: 'post-tenebras-rock',
    id: '22',
    type: 'graphic',
    year: '2012',
    tags: ['Visual-Identity', 'Poster'],
    horizontal: false,
    mp4: false,
    image: '/CoverPhotos/Galleries/PostTenebrasRock.jpg',
    img1: '/PostTenebrasRock/1.jpg',
    sources: [
      {
        type: 'img',
        img: '/PostTenebrasRock/2.jpg',
      },
      {
        type: 'img',
        img: '/PostTenebrasRock/3.jpg',
      },
      {
        type: 'img',
        img: '/PostTenebrasRock/4.jpg',
      },
      {
        type: 'img',
        img: '/PostTenebrasRock/5.jpg',
      },
      {
        type: 'img',
        img: '/PostTenebrasRock/6.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/PostTenebrasRock/7.jpg',
        rows: 2,
        cols: 2,
      },
    ],
    attributes: {
      description:
        "Posters & flyers proposition for Post Tenebras Rock (2011) concerts at l'Usine, Geneva.This is a platform for young new artists to perform and potentially launch their career. This is a place where many renown artists were ‘born’. Hence, I felt the idea of fertilization was highly relevant as I believe it clearly echoes all these young artists competing to get to the stage, to stand out, to be the best, and eventually be the one that makes it to become an artist.",
    },
  },
  {
    name: 'Thesaurus',
    slug: 'thesaurus',
    id: '23',
    type: 'typeface',
    year: '2017',
    tags: ['Visual-Identity'],
    horizontal: true,
    mp4: false,
    landing: '/CoverPhotos/Lading/Thesaurus.jpg',
    image: '/CoverPhotos/Galleries/Thesaurus.jpg',
    sources: [
      {
        type: 'img',
        img: '/Thesaurus/1.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Thesaurus/2.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Thesaurus/3.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Thesaurus/4.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Thesaurus/6.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Thesaurus/7.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Thesaurus/9.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Thesaurus/10.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Thesaurus/11.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Thesaurus/12.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Thesaurus/13.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Thesaurus/14.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Thesaurus/26.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Thesaurus/15.jpg',
        rows: 2,
        cols: 4,
      },

      {
        type: 'img',
        type: 'img',
        img: '/Thesaurus/17.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Thesaurus/18.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Thesaurus/19.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Thesaurus/20.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Thesaurus/21.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Thesaurus/22.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Thesaurus/23.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Thesaurus/24.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Thesaurus/25.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Thesaurus/16.jpg',
        rows: 2,
        cols: 4,
      },
    ],
    attributes: {
      description:
        'Thesaurus is a super type-family (16 styles) with one foot in the past & one foot in the present which was inspired by the typographic history of the city of Geneva.Thesaurus is based on the types that Robert Estienne brought from Paris to Geneva, which were later used by his son Henri II Estienne for printing the famous book "Thesaurus Græcæ Linguæ" in 1572. These metal types served, in some way, as a bridge between France and Switzerland, between Catholicism and Protestantism, and now, through Thesaurus, between past and present. Thesaurus had a first release in January 2017 and was further extended in 2018 adding the Display Italic styles, making Thesaurus sharper and even more dignified. These new styles were developed taking into consideration the feedback I\'ve got from Thesaurus\' first users. The creation of the Display Italic styles requested me to rethink many of the original terminations and remove optical compensations designed to enhance small sizes.  Thesaurus has received the Gold award (first prize) at the European Design Awards 2018 and the Gold Award & Best Project of Category at the LAD - Latin American Design Awards 2019. Furthermore, it was one of the 4 projects awarded with the Mention of Excellence at the 8th Latin-American type-design biennial by Tipos Latinos (TL8) – out of 444 projects submitted this year. It was selected in the Superfamily category. It has also been awarded with Gold in the Graphis Type 4: Typeface Design Competition. Get Thesaurus at Typotheque.com',
    },
  },
  {
    name: 'Tijuana Panthers',
    slug: 'tijuana-panthers',
    id: '24',
    type: 'graphic',
    year: '2014',
    tags: ['Illustration', 'Poster'],
    horizontal: true,
    mp4: false,
    landing: '/CoverPhotos/Lading/TijuanaPanthers.jpg',
    image: '/CoverPhotos/Galleries/TijuanaPanthers.jpg',
    sources: [
      {
        type: 'img',
        img: '/TijuanaPanthers/1.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TijuanaPanthers/3.jpg',
        rows: 2,
        cols: 2,
      },

      {
        type: 'img',
        img: '/TijuanaPanthers/2.jpg',
        rows: 2,
        cols: 4,
      },
    ],
    attributes: {
      description:
        'I was asked by Rock This Town (association which organises concerts in Geneva) to design a poster to promote the concert of Californian band Tijuana Panthers.',
    },
  },
  {
    name: 'Time Out',
    slug: 'time-out',
    id: '25',
    type: 'graphic',
    year: '2013',
    tags: ['Cover-Design'],
    horizontal: true,
    mp4: false,
    landing: '/CoverPhotos/Lading/TimeOut.jpg',
    image: '/CoverPhotos/Galleries/TimeOut.jpg',
    sources: [
      {
        type: 'img',
        img: '/TimeOut/1.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TimeOut/3.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TimeOut/4.jpg',
        rows: 1,
        cols: 2,
      },
    ],
    attributes: {
      description:
        'The New York magazine TimeOut asked me to design the cover of its "spring preview" issue (late February, 2013), and wanted me to reinvent my "Beyond the Box" poster (link this). For me, spring is about flowers, paper windmills and kaleidoscopes, so my visual concept was inspired by this mood board.',
    },
  },
  {
    name: 'Tomorrow',
    slug: 'tomorrow',
    id: '26',
    type: 'graphic',
    year: '2013',
    tags: ['Poster'],
    horizontal: false,
    mp4: false,
    landing: '/CoverPhotos/Lading/Tomorrow.jpg',
    image: '/Tomorrow/1.jpg',
    img1: '/Tomorrow/5.jpg',
    sources: [
      {
        type: 'img',
        img: '/Tomorrow/1.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Tomorrow/2.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Tomorrow/4.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Tomorrow/3.jpg',
        rows: 2,
        cols: 2,
      },
    ],
    attributes: {
      description:
        "The poster flirts with the concepts of luck and randomness, which are strongly related to the idea of future (tomorrow), since no matter how much effort we put into it, things might not turn out the way we'/d planned.",
    },
  },
  {
    name: 'Typography Heroes',
    slug: 'typography-heroes',
    id: '27',
    type: 'typeface',
    year: '2013',
    tags: ['Poster'],
    horizontal: true,
    mp4: false,
    landing: '/CoverPhotos/Lading/TypographyH.jpg',
    image: '/CoverPhotos/Galleries/TypographicHeroes.jpg',
    sources: [
      {
        type: 'img',
        img: '/TypographyHeroes/1.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/2.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/3.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/4.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/5.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/6.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/7.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/9.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/10.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/11.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/13.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/12.JPG',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/14.JPG',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/15.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/17.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/18.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/21.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/22.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/24.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/25.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/26.jpg',
        rows: 2,
        cols: 2,
      },

      {
        type: 'img',
        img: '/TypographyHeroes/28.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/29.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/30.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/31.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/32.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/TypographyHeroes/33.jpg',
        rows: 2,
        cols: 2,
      },

      {
        type: 'img',
        img: '/TypographyHeroes/16.jpg',
        rows: 2,
        cols: 4,
      },

      {
        type: 'img',
        img: '/TypographyHeroes/23.jpg',
        rows: 2,
        cols: 4,
      },
    ],
    attributes: {
      description:
        'My concept was to combine two printing techniques; One of the latest: the Risograph (RISO), with one of the oldest printing methods: movable type page setting and press printing. First of all, the portrait images were printed with the RISO. Then, all the texts were composed by hand printing over the portraits using a press. I chose these 4 designers taking in consideration several aspects: the impact their typefaces had in the world of typography and the availability of the metal characters at school. I also picked these 4 designers because they all lived in a different period of time. Therefore they faced different problems. Their work somehow represents the evolution in typography This is a school project in progress, the two other posters will be up soon.',
    },
  },
  {
    name: 'Viga',
    slug: 'viga',
    id: '28',
    type: 'typeface',
    year: '2011',
    tags: null,
    horizontal: false,
    mp4: false,
    image: '/Viga/7.jpg',
    img1: '/Viga/1.jpg',
    sources: [
      {
        type: 'img',
        img: '/Viga/2.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Viga/3.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Viga/4.jpg',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Viga/7.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Viga/6.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Viga/5.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Viga/8.jpg',
        rows: 2,
        cols: 2,
      },
    ],
    attributes: {
      description:
        'Viga is an experimental capitals-only display font influenced by constructivism, with a high level of abstraction. The grid I created for developing Viga was inspired by truss beams used in architecture.',
    },
  },
  {
    name: 'Weltformat',
    slug: 'weltformat',
    id: '29',
    type: 'graphic',
    year: '2011',
    tags: ['Poster'],
    horizontal: false,
    mp4: false,
    landing: '/CoverPhotos/Lading/Weltformat.jpg',
    image: '/CoverPhotos/Galleries/Weltformat.jpg',
    img1: '/Weltformat/5.jpg',
    sources: [
      {
        type: 'img',
        img: '/Weltformat/1.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Weltformat/2.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Weltformat/3.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Weltformat/4.jpg',
        rows: 2,
        cols: 2,
      },
    ],
    attributes: {
      description:
        'Finalist in the students\' international contest of the Weltformat 11 poster festival, Luzern, Switzerland. This poster was chosen between more than 400 students of 20 different countries as a response to the theme "Poster for the Poster". The brief: The posters are reflections of the society that views them and for whom they are produced and hung in masses. The high requests and the interest from society are reflected in this fascinating media: its needs, its wishes and its dreams. The students are being challenged to consider the advantages and the powers of posters as an advertisement- and communication media. Posters for the poster - this must be the visual statement of the poster design. My poster was exhibited across Luzern during the Weltformat festival. http://www.weltform.at/',
    },
  },
  {
    name: 'Brick',
    slug: 'brick',
    id: '30',
    type: 'typeface',
    year: '2019',
    tags: null,
    horizontal: true,
    mp4: false,
    landing: '/CoverPhotos/Lading/BrickTypefamily.jpg',
    image: '/CoverPhotos/Galleries/BrickTypefamilyLandscape.jpg',
    sources: [
      {
        type: 'img',
        img: '/Brick/2.jpg',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Brick/3.jpg',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Brick/4.jpg',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Brick/5.jpg',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Brick/6.jpg',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Brick/7.jpg',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Brick/8.jpg',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Brick/9.jpg',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Brick/10.jpg',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Brick/11.jpg',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Brick/12.jpg',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Brick/13.jpg',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Brick/14.jpg',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Brick/15.jpg',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Brick/16.jpg',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Brick/17.jpg',
        rows: 4,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Brick/18.jpg',
        rows: 4,
        cols: 4,
      },
    ],
    attributes: {
      description:
        "Brick’s foundations lie in the signage of three prominent pubs in London’s East End, The Jolly Butchers (Brick Lane – now closed), The Royal Oak (Columbia Road), and The Prince Albert (Acton Street). Referencing their Art Deco traits, with a trace of Art Nouveau heritage, Brick is Fermín Guerrero’s re-interpretation and continuation of the vernaculars elegant gestures, brought into the 21st century. Guerrero first discovered the vernacular of Brick Lane street during one of his visits to London, in 2015, while studying Typeface Design in Reading. It wasn’t until several years later that the collective forms and development of the design began to materialise. Brick was initially released in 2019, in three weights, and was further extended in 2020 becoming a five weights (ExtraLight, Light, Regular, Medium & Black) type family, across two optical sizes (Text & Display) and it is available to license exclusively through www.Colophon-Foundry.com, in both Standard (‘STD’) and Professional (‘PRO’) versions. The latter encapsulates the prominent Truman brewery’s unique personality through an exhaustive series of OpenType features and stylistic alternates available within the PRO variant. If you want to know more about Brick's development, don't miss the article I wrote with Colophon, where you can learn a lot more about the project",
      urlDescription:
        'https://medium.com/@Colophon/brick-a-new-font-brewing-e2a982e39c8f',
    },
  },
  {
    name: 'Architecture +',
    slug: 'architecture-+',
    id: '31',
    type: 'graphic',
    year: '2020',
    tags: ['Visual-Identity', 'Animation', 'Editorial'],
    horizontal: false,
    mp4: true,
    mp4Video: '/Architecture/forGalleryShorter.mp4',
    mp41: '/Architecture/Cover.mp4',
    sources: [
      {
        type: 'img',
        img: '/Architecture/S1/0.png',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Architecture/S1/3.jpg',
        rows: 2,
        cols: 2,
      },

      {
        type: 'img',
        img: '/Architecture/S1/5.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Architecture/S1/7.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Architecture/S1/12.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'video',
        url: '/Architecture/S1/2.mp4',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Architecture/S1/13.png',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Architecture/S1/14.png',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Architecture/S2/0.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'video',
        url: '/Architecture/S2/1.mp4',
        rows: 2,
        cols: 2,
      },
      {
        type: 'video',
        url: '/Architecture/S2/2.mp4',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Architecture/S2/3.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'video',
        url: '/Architecture/S2/4.mp4',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Architecture/S2/5.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'video',
        url: '/Architecture/S2/6.mp4',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Architecture/S2/7.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'video',
        url: '/Architecture/S2/8.mp4',
        rows: 2,
        cols: 2,
      },
      {
        type: 'video',
        url: '/Architecture/S2/6.mp4',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Architecture/S2/7.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'video',
        url: '/Architecture/S2/8.mp4',
        rows: 2,
        cols: 2,
      },
      {
        type: 'video',
        url: '/Architecture/S2/9.mp4',
        rows: 2,
        cols: 2,
      },
      {
        type: 'video',
        url: '/Architecture/S2/10.mp4',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Architecture/S2/11.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'video',
        url: '/Architecture/S3/1.mp4',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Architecture/S3/2.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Architecture/S3/3.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Architecture/S3/4.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Architecture/6.png',
        rows: 2,
        cols: 2,
      },
      {
        type: 'video',
        url: '/Architecture/forGallery.mp4',
        rows: 2,
        cols: 2,
      },
      {
        type: 'video',
        url: '/Architecture/S3/Mina.mp4',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Architecture/1.png',
        rows: 2,
        cols: 4,
      },
      {
        type: 'video',
        url: '/Architecture/S3/Ali.mp4',
        rows: 2,
        cols: 2,
      },
      {
        type: 'video',
        url: '/Architecture/S3/Comp.mp4',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/Architecture/2.png',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Architecture/3.png',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Architecture/4.png',
        rows: 2,
        cols: 4,
      },
      {
        type: 'img',
        img: '/Architecture/5.png',
        rows: 2,
        cols: 4,
      },
    ],
    attributes: {
      description:
        "Visual-Identity for Sharjah Architecture Triennial's series of podcasts.ARCHITECTURE + is a series of online conversations that aim to create dialogues exploring the social responsibilities of architects, urban planners, academics and their multidisciplinary interlocutors. Times of crisis, such as the current pandemic, demand that we question what we value in our respective disciplines and collectively rethink environmental and social sustainability at various scales. The ‘+’ is the connection, allowing us to mix and combine. It becomes the sight, the window that enables us to zoom in and out, to look closer and further, to focus and to see differently. You can listen to the podcasts",
      urlDescription:
        'https://www.sharjaharchitecture.org/pages/programs/architecture-plus',
    },
  },
  {
    name: 'Beyond The Box',
    slug: 'beyond-the-box',
    id: '32',
    type: 'graphic',
    year: '2011',
    tags: ['Visual-Identity', 'Poster'],
    horizontal: true,
    mp4: false,
    landing: '/BeyondTheBox/1.jpg',
    image: '/BeyondTheBox/1.jpg',
    sources: [
      {
        type: 'img',
        img: '/BeyondTheBox/2.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/BeyondTheBox/3.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/BeyondTheBox/4.jpg',
        rows: 1,
        cols: 2,
      },

      {
        type: 'img',
        img: '/BeyondTheBox/5.jpg',
        rows: 1,
        cols: 1,
      },
      {
        type: 'img',
        img: '/BeyondTheBox/9.jpg',
        rows: 1,
        cols: 2,
      },
      {
        type: 'img',
        img: '/BeyondTheBox/7.jpg',
        rows: 1,
        cols: 1,
      },
      {
        type: 'img',
        img: '/BeyondTheBox/8.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/BeyondTheBox/6.jpg',
        rows: 2,
        cols: 2,
      },
      {
        type: 'img',
        img: '/BeyondTheBox/10.jpg',
        rows: 2,
        cols: 4,
      },
    ],
    attributes: {
      description:
        'Identity, flyer and Poster design for an art exhibition under the theme Supergraphics. School project.',
    },
  },
]

export default projects
