const projects = [
  {
    name: 'Carte Blanche',
    id: '1',
    type: "graphic",
    year: '2013',
    image: '/CoverPhotos/Galleries/CarteBlancheH.jpg',
    images: {
      img1: '/CartaBlanche/1.jpg',
      img2: '/CartaBlanche/2.JPG',
      img3: '/CartaBlanche/3.JPG',
      img4: '/CartaBlanche/4.JPG',
      img5: '/CartaBlanche/5.JPG',
      img6: '/CartaBlanche/6.JPG',
      img7: '/CartaBlanche/7.JPG'
    },
    attributes: {
      description:'I had the honor of being invited by Form magazine to design a poster for their "Carte Blanche" limited edition poster series, for their May/June 2013 issue, in collaboration with the Berlin furniture design Studio Hausen.'
    },
  },
  {
    name: 'Circ',
    id: '2',
    type: "typeface",
    year: '2011',
    image: '/CoverPhotos/Galleries/CircH.jpg',
    images: {
      img1: '/Circ/1.JPG',
      img2: '/Circ/2.JPG',
      img3: '/Circ/3.JPG',
      img4: '/Circ/4.JPG',
      img5: '/Circ/5.JPG',
      img6: '/Circ/6.JPG',
      img7: '/Circ/7.JPG'
    },
    attributes: {
      description:'CIRC is an experimental title font, based on geometic forms deriving from the circle.'
    },
  },
  {
    name: 'DinMachine',
    id: '3',
    type: "graphic",
    year: '2014',
    landing: '/CoverPhotos/Lading/DinMachine.jpg',
    image: '/CoverPhotos/Galleries/DinMachine.jpg',
    images: {
      img1: '/DinMachine/1.jpg',
      img2: '/DinMachine/2.jpg',
      img3: '/DinMachine/3.jpg',
      img4: '/DinMachine/4.jpg',
      img5: '/DinMachine/5.jpg',
      img6: '/DinMachine/6.jpg',
      img7: '/DinMachine/7.jpg',
      img8: '/DinMachine/8.jpg',
      img9: '/DinMachine/9.jpg',
      img10: '/DinMachine/10.jpg',
      img11: '/DinMachine/11.jpg',
      img12: '/DinMachine/12.jpg',
      img13: '/DinMachine/13.jpg',
      img14: '/DinMachine/14.jpg',
      img15: '/DinMachine/15.jpg',
      img16: '/DinMachine/16.jpg',
      img17: '/DinMachine/17.jpg',
      img18: '/DinMachine/18.jpg',
      img19: '/DinMachine/19.jpg',
      img20: '/DinMachine/20.jpg',
      img21: '/DinMachine/21.jpg',
      img22: '/DinMachine/22.jpg',
      img23: '/DinMachine/23.jpg',
      img24: '/DinMachine/24.jpg',
      img25: '/DinMachine/25.jpg',
      img26: '/DinMachine/26.jpg',
      img27: '/DinMachine/27.jpg',
    },
    attributes: {
      description:'Logo and CD cover design for the New York based electronic experimental rock band DinMachine Created for their first album �Dance to reason. I also designed a t-shirt to accompany the CD launching. DinMachine is a collaboration between Nisi Jacobs and Michael J. Schumacher. They have been making music together since 2009 and have performed at MoMA New York. Ken Jacobs (a world renowned experimental film maker) has used both Schumacher�s and DinMachine�s music for his published films. Asking Nisi and Michael about themselves, the band and the music they create together, they came up with some things that I found very interesting to work graphically on: We want to grab people with the music, get them moving. DinMachine�s music has been generally described as non-classifiable. Our music, we feel, has elements that are very engaging and involving, and others that need distance and detachment. We like the idea of hot vs cold, engaging sexiness. For the logo, I decided to work with the idea of both �non-classifiable� as well as contrast/opposite. My approach to the logo was very experimental, mixing uppercase and lowercase letters in order to create something of an originality which defies classification. The letters are all cut differently which adds movement and vibration to the logo which echoes DinMachine\'/s music. For the CD cover I created a concept which plays with the idea of sexiness, opposite (cold vs hot, engage/detach) and movement. From a distance you can see an abstract image, an involving composition of a mix of colors and shapes. But when looking closely, you discover the details, a scene containing human bodies, people moving combined with something as coldand lifeless as dry black trees. The inside vs the outside of the cover also plays with this idea of contrast/opposite..'
    },
  },
  {
    name: 'Exentra',
    id: '4',
    type: "typeface",
    year: '2015',
    landing: '/CoverPhotos/Lading/Exentra.jpg',
    image: '/CoverPhotos/Galleries/ExentraV.jpg',
    images: {
      img1: '/Exentra/1.jpg',
      img2: '/Exentra/2.JPG',
      img3: '/Exentra/3.JPG',
      img4: '/Exentra/4.JPG',
      img5: '/Exentra/5.JPG',
      img6: '/Exentra/6.JPG',
      img7: '/Exentra/7.JPG',
      img8: '/Exentra/8.jpg',
      img9: '/Exentra/9.jpg',
      img10: '/Exentra/10.jpg',
      img11: '/Exentra/11.jpg',
      img12: '/Exentra/12.jpg',
      img13: '/Exentra/13.jpg',
      img14: '/Exentra/14.jpg',
      img15: '/Exentra/15.jpg',
      img16: '/Exentra/16.jpg',
      img17: '/Exentra/17.jpg',
      img18: '/Exentra/18.jpg',
      img19: '/Exentra/19.jpg',
      img20: '/Exentra/20.jpg',
      img21: '/Exentra/21.jpg',
      img22: '/Exentra/22.jpg',
      img23: '/Exentra/23.jpg',
      img24: '/Exentra/24.jpg',
      img25: '/Exentra/25.jpg',
      img26: '/Exentra/26.jpg',
      img27: '/Exentra/27.jpg',
      img28: '/Exentra/28.jpg',
    },
    attributes: {
      description:'Exentra is the project I developed at the MATD course 2014-15, in Reading. My intention for the MATD project was to design an innovative and unique typeface that would appeal to designers doing forward-looking design. Therefore, this Typeface family was concevied for publications promoting forward-thinking through a contemporary and experimental vision of modern culture and trends. Its style combines the elegance and warmth of calligraphy with the precision and digital sharpness of the computer process that give it a contemporary look. Unconventional letter shapes, and the playful and dynamic design, reinforce the idiosyncrasy of the typeface. Exentra consist of Latin (7 cuts for the text version, Italic, Sans Serif and two Display versions) Gurmukhi and Greek. The images below belong to Exentra�s Specimen Book. Don\'/t hesitate to request the pdf version of the Specimen.'
    },
  },
  {
    name: 'Feria Del Libro',
    id: '5',
    type: "graphic",
    year: '2018',
    landing: '/CoverPhotos/Lading/FeriaDelLibro.jpg',
    image: '/CoverPhotos/Galleries/FeriaDelLibro.jpg',
    images: {
      img1: '/FeriaDelLibro/1.jpg',
      img2: '/FeriaDelLibro/2.jpg',
      img3: '/FeriaDelLibro/3.jpg',
      img4: '/FeriaDelLibro/4.jpg',
    },
    attributes: {
      description:'Proposition I made for the poster competition for the "18th Book Fair for children and young people" in Uruguay - which I did not win. My intention was to create an image that would show books in a playful and intriguing manner, that would appeal to kids\'/ curiosity and encourage them to go explore the discoveries opportunities a book faire offers. More generally, I wanted kid to perceive a book faire as an exciting place to visit. My mottos were: Knowledge is freedom. Reading is fun.'      
    },
  },
  {
    name: 'Fédération Genevoise de Coopération',
    id: '6',
    type: "graphic",
    year: '2012',
    landing: '/CoverPhotos/Lading/FGC.jpg',
    image: '/CoverPhotos/Galleries/FGC.jpg',
    images: {
      img1: '/FGC/1.jpg',
      img2: '/FGC/2.jpg',
      img3: '/FGC/3.jpg',
      img4: '/FGC/4.jpg',
      img5: '/FGC/5.jpg',
      img6: '/FGC/6.gif',
      img7: '/FGC/7.gif',
      img8: '/FGC/8.jpg',
      img9: '/FGC/9.gif',
      img10: '/FGC/10.jpg',
      img11: '/FGC/11.JPG',
      img12: '/FGC/12.JPG',
      img13: '/FGC/13.JPG',
      img14: '/FGC/14.JPG',
      img15: '/FGC/15.JPG',
      img16: '/FGC/16.JPG',
      img17: '/FGC/17.jpg',
      img18: '/FGC/18.jpg',
      img19: '/FGC/19.jpg',
      img20: '/FGC/20.jpg',
      img21: '/FGC/21.jpg',
      img22: '/FGC/22.jpg',
      img23: '/FGC/23.jpg',
      img24: '/FGC/24.jpg',
      img25: '/FGC/25.jpg',
      img26: '/FGC/26.jpg',
      img27: '/FGC/27.jpg',
      img28: '/FGC/28.jpg',
      img29: '/FGC/29.jpg',
      img30: '/FGC/30.jpg',
      img31: '/FGC/31.jpg',
    },
    attributes: {
      description:'First prize in the contest for the re-design of Fédération Genevoise de Coopération\'/s corporate identity - 2012. The FGC regroups about fifty associations with headquarters in Geneva. The aim behind this cooperation is to aid developing countries and raise public awareness. Therefore, the Fédération Genevoise de Coopération finances projects which help battle inequality and provide freedom of choice to these countries.'      
    },
  },
  {
    name: 'Flag Of Peace',
    id: '7',
    type: "graphic",
    year: '2017',
    landing: '/CoverPhotos/Lading/FlagOfPeace.jpg',
    image: '/CoverPhotos/Galleries/FlagOfPeace.jpg',
    images: {
      img1: '/FlagOfPeace/1.jpg',
      img2: '/FlagOfPeace/2.jpg',
      img3: '/FlagOfPeace/3.jpg',
      img4: '/FlagOfPeace/4.jpg',
      img5: '/FlagOfPeace/5.jpg',
      img6: '/FlagOfPeace/6.jpg',
      img7: '/FlagOfPeace/7.jpg',
      img8: '/FlagOfPeace/8.jpg',
    },
    attributes: {
      description:'Flags of Peace (NL) honoured me with an invitation to design an international peace flag to represent my country (Uruguay) in their international exhibition Flags of Peace which travels around the world. Many bold designers and studios have already joined the great cause behind this project by designing the flag for their respective countries. My thoughts: I believe that for a flag to be International it has to represent/address all cultures equally. Therefore, we cannot rely on words, since language only represent a certain culture. Although there are some symbols that are internationally associate with peace, when looking at their origins, research showed me that, for the most part, their either represented something else or were linked to a specific religion. Accordingly, the use of them was judged inappropriate. There are normally two sides in a conflict putting peace away, where either two persons, or groups (nations, towns, etc.) are confronted for things such as religion, genre, skin color, social class, origins, and so on. For peace to take place, these two sides need to come to terms and see each other as equals in order to impart mutual respect. Concept: My flag carries a message of hope, showing these opposite sides finding common ground, complementing each other and sharing instead of dividing and excluding. Symmetry was used as means of representing equality and balance between two sides that although they look different (color), they are equals (form). The symmetrical image is also an analogy for a mirror, encouraging people to find a piece of themselves in the one in front of us.'      
    },
  },
  {
    name: 'Freedom Of Movement',
    id: '8',
    type: "graphic",
    year: '2017',
    image: '/CoverPhotos/Galleries/FreedomOfMovement.jpg',
    images: {
      img1: '/FreedomOfMovement/1.jpg',
      img2: '/FreedomOfMovement/2.jpg',
      img3: '/FreedomOfMovement/3.jpg',
      img4: '/FreedomOfMovement/4.jpg',
    },
    attributes: {
      description:''      
    },
  },
  {
    name: 'Geneva Motor Show',
    id: '9',
    type: "graphic",
    year: '2014',
    landing: '/CoverPhotos/Lading/GenevaMotorShow.jpg',
    image: '/CoverPhotos/Galleries/GenevaMotorShow.jpg',
    images: {
      img1: '/GenevaMotorShow/1.jpg',
      img2: '/GenevaMotorShow/2.jpg',
      img3: '/GenevaMotorShow/3.jpg',
      img4: '/GenevaMotorShow/4.jpg',
      img5: '/GenevaMotorShow/5.jpg',
      img6: '/GenevaMotorShow/6.jpg',
      img7: '/GenevaMotorShow/7.jpg',
      img8: '/GenevaMotorShow/8.jpg',
      img9: '/GenevaMotorShow/9.jpg',
      img10: '/GenevaMotorShow/10.jpg',
      img11: '/GenevaMotorShow/11.JPG',
      img12: '/GenevaMotorShow/12.JPG',
      img13: '/GenevaMotorShow/13.JPG',
      img14: '/GenevaMotorShow/14.JPG',
      img15: '/GenevaMotorShow/15.JPG',
      img16: '/GenevaMotorShow/16.JPG',
      img17: '/GenevaMotorShow/17.jpg',
      img18: '/GenevaMotorShow/18.jpg',
      img19: '/GenevaMotorShow/19.jpg',
      img20: '/GenevaMotorShow/20.jpg',
      img21: '/GenevaMotorShow/21.jpg',
      img22: '/GenevaMotorShow/22.jpg',
      img23: '/GenevaMotorShow/23.jpg',
      img24: '/GenevaMotorShow/24.jpg',
      img25: '/GenevaMotorShow/25.jpg',
      img26: '/GenevaMotorShow/26.jpg',
      img27: '/GenevaMotorShow/27.jpg',
      img28: '/GenevaMotorShow/28.jpg',
      img29: '/GenevaMotorShow/29.jpg',
      img30: '/GenevaMotorShow/30.jpg',
      img31: '/GenevaMotorShow/31.jpg',
    },
    attributes: {
      description:'1rst Prize at the contest, holded by HEAD, for Geneva Motor Show 2014\'/s poster design and art direction. This graphic was used in all of the different national and international communication campaigns for the 2014 Geneva International Motor Show. I wanted to propose a different design concept that goes further than the � regular � style of the Motor Show. Therefore I wanted to avoid the typical representative car and automobile references and busy images. I also noticed that quite often in the previous poster campaigns, text and image were treated as two completely distinct elements and were therefore very distant from one another. The text took the shape of a rigid block that was very often placed the same way on all the visual identity media. My goal was to create, on one hand, an uncluttered, minimal and abstract design that evokes feelings and emotions related to the automobile sector and to bring outthe positive aspects of the Motor Show (speed, movement, freedom, diversity and joy) more than concentrate on the actual car itself. On the other hand, I wanted to make the text the protagonist element of my design. The creation and composition of the poster is entirely drawn out typographically. I propose a design with different reading levels, where the lines suggest a network of roads which evoke the number of visitors coming to visit the Motor Show every year from around the world. They also insinuate the shape of certain elements that are part of the traditional Genevan landscape: Cars, mountains, the Jet D\'/eau, etc. As for the colours, I was inspired by the season in which the Geneva Motor Show takes place, spring. '
    },
  },
  {
    name: 'Genève Typeface',
    id: '10',
    type: "typeface",
    year: '2014',
    landing: '/CoverPhotos/Lading/GeneveTypeface.jpg',
    image: '/CoverPhotos/Galleries/GeneveTypeface.jpg',
    images: {
      img1: '/GeneveTypeface/1.jpg',
      img2: '/GeneveTypeface/2.jpg',
      img3: '/GeneveTypeface/3.jpg',
      img4: '/GeneveTypeface/4.jpg',
      img5: '/GeneveTypeface/5.jpg',
      img6: '/GeneveTypeface/6.jpg',
      img7: '/GeneveTypeface/7.jpg',
      img8: '/GeneveTypeface/8.jpg',
      img9: '/GeneveTypeface/9.jpg',
      img10: '/GeneveTypeface/10.jpg',
      img11: '/GeneveTypeface/11.JPG',
      img12: '/GeneveTypeface/12.JPG',
      img13: '/GeneveTypeface/13.JPG',
      img14: '/GeneveTypeface/14.JPG',
      img15: '/GeneveTypeface/15.JPG',
      img16: '/GeneveTypeface/16.JPG',
      img17: '/GeneveTypeface/17.jpg',
      img18: '/GeneveTypeface/18.jpg',
      img19: '/GeneveTypeface/19.jpg',
      img20: '/GeneveTypeface/20.jpg',
      img21: '/GeneveTypeface/21.jpg',
      img22: '/GeneveTypeface/22.jpg',
      img23: '/GeneveTypeface/23.jpg',
      img24: '/GeneveTypeface/24.jpg',
      img25: '/GeneveTypeface/25.jpg',
      img26: '/GeneveTypeface/26.jpg',
      img27: '/GeneveTypeface/27.jpg',
      img28: '/GeneveTypeface/28.jpg',
      img29: '/GeneveTypeface/29.jpg',
      img30: '/GeneveTypeface/30.jpg',
      img31: '/GeneveTypeface/31.jpg',
      img32: '/GeneveTypeface/32.jpg',
      img33: '/GeneveTypeface/33.jpg',
      img34: '/GeneveTypeface/34.jpg',
      img35: '/GeneveTypeface/35.jpg',
      img36: '/GeneveTypeface/36.jpg',
      img37: '/GeneveTypeface/37.jpg',
      img38: '/GeneveTypeface/38.jpg',
      img39: '/GeneveTypeface/39.jpg',
      img40: '/GeneveTypeface/40.jpg',
      img41: '/GeneveTypeface/41.JPG',
      img42: '/GeneveTypeface/42.JPG',
      img43: '/GeneveTypeface/43.JPG',
      img44: '/GeneveTypeface/44.JPG',
      img45: '/GeneveTypeface/45.JPG',
      img46: '/GeneveTypeface/46.JPG',
      img47: '/GeneveTypeface/47.jpg',
      img48: '/GeneveTypeface/48.jpg',
      img49: '/GeneveTypeface/49.jpg',
      img50: '/GeneveTypeface/50.jpg',
      img51: '/GeneveTypeface/51.jpg',
      img52: '/GeneveTypeface/52.jpg',
      img53: '/GeneveTypeface/53.jpg',
      img54: '/GeneveTypeface/54.jpg',
      img55: '/GeneveTypeface/55.jpg',
      img56: '/GeneveTypeface/56.jpg',
      img57: '/GeneveTypeface/57.jpg',
      img58: '/GeneveTypeface/58.jpg',
      img59: '/GeneveTypeface/59.jpg',
      img60: '/GeneveTypeface/59b.jpg',
      img61: '/GeneveTypeface/60.jpg',
      img62: '/GeneveTypeface/61.jpg',
      img63: '/GeneveTypeface/62.jpg',
      img64: '/GeneveTypeface/63.jpg',
    },
    attributes: {
      description:'Geneve is a type family inspired by the rich typographic history of Geneva.- Bachelor thesis at HEAD, Geneva - Designed to be used on any type of printed support, Gen�ve is a typography with personality and flexibility, which allows designers to express their ideas in different ways without losing coherence. In developing Gen�ve I was inspired by the typeface used by French printer/editor/publisher Henri II Estienne in his famous book Thesaurus Lingu� Gr�c�, published in Geneva in 1572. This typeface was brought to Geneva by Henri�s father, Robert Estienne, who, before settling in Geneva and working as Calvin�s printer, was the printer of France�s King, Fran�ois I. This typeface highly influenced the typographers and printers in Geneva at that time. Henri and Robert Estienne�s work in Geneva helped it to become one of the most important cities in Europe for print and typography in the sixteenth century. Gen�ve consists of four styles: Classique (Humanist serif), Aust�re (Geometric serif), Spontan�e (Humanist sans-serif) and Alternative (Stencil, display version). These styles correspond to the different profiles of the city, reflecting its multiculturalism and diversity. This typography acts as a bridge between the past and present of the city. I received the BEA Fondation Award for Young Artists for my work on the Gen�ve Typeface.'
    },
  },

  {
    name: 'Goes Around',
    id: '11',
    type: "graphic",
    year: '2014',
    image: '/CoverPhotos/Galleries/GoesArround.jpg',
    images: {
      img1: '/GoesAround/1.jpg',
      img2: '/GoesAround/2.jpg',
      img3: '/GoesAround/3.jpg',
      img4: '/GoesAround/4.jpg',
    },
    attributes: {
      description:'For a school project in collaboration with the RATP (Parisian autonomous transport society), we were asked to create a 10 second long animation to wish the passengers a happy new year 2014. The animations were shown on the large HD screens at the Franklin Roosevelt and Europe metro stops in Paris, France, from December 24, 2013 to January 8, 2014. My intention was to confront themselves, that they reflect on who they are and how they behave with others. I found this most interesting and thought that I could respond to this in various ways. Therefore I decided to also create two posters: one derived from the animation and the other, completely independent - Both with no intention of being shown on the RATP -. For the independent poster �2014 goes around...comes around� (see above), I handled the subject in a more explicit and trashy way.'
    },
  },
  {
    name: 'Its up to you',
    id: '12',
    type: "graphic",
    year: '2014',
    landing: '/CoverPhotos/Lading/ItsUpToYou.jpg',
    image: '/CoverPhotos/Galleries/ItsUpToYou.jpg',
    images: {
      img1: '/ItsUpToYou/1.jpg',
      img2: '/ItsUpToYou/2.jpg',
      img3: '/ItsUpToYou/3.jpg',
      img4: '/ItsUpToYou/4.jpg',
      img5: '/ItsUpToYou/5.jpg',
      img6: '/ItsUpToYou/6.jpg',
      img7: '/ItsUpToYou/7.jpg',
      img8: '/ItsUpToYou/8.jpg',
      img9: '/ItsUpToYou/9.jpg',
      img10: '/ItsUpToYou/10.jpg',
      img11: '/ItsUpToYou/11.JPG',
      img12: '/ItsUpToYou/12.JPG',
      img13: '/ItsUpToYou/13.JPG',
      img14: '/ItsUpToYou/14.JPG',
      img15: '/ItsUpToYou/15.JPG',
      },
    attributes: {
      description:'For a school project in collaboration with the RATP (Parisian autonomous transport society), we were asked to create a 10 second long animation to wish the passengers a happy new year 2014 The animations were shown on the large HD screens at the Franklin Roosevelt and Europe metro stops in Paris, France, from December 24, 2013 to January 8, 2014. My intention was to make people to confront themselves so that they reflect on who they are and how they behave with others. I found this most interesting and thought that I could respond to this in various ways. Therefore I decided to also create two posters: one derived from the animation and the other completely independent - both with no intention of being shown on the RATP. I inserted a small text in the center of the mirror. This text aims to make people approach and get up close to the poster in order to read the sentence it\'/s up to you, and at the same time, they see themselves in the mirror and are confronted to themselves.'   
     },
  },
  {
    name: 'Jeu de regards',
    id: '13',
    type: "graphic",
    year: '2012',
    landing: '/CoverPhotos/Lading/JoieDeLire.jpg',
    image: '/CoverPhotos/Galleries/JoieDeLire.jpg',
    images: {
      img1: '/JoieDeLire/1.jpg',
      img2: '/JoieDeLire/2.JPG',
      img3: '/JoieDeLire/3.JPG',
      img4: '/JoieDeLire/4.JPG',
      img5: '/JoieDeLire/5.JPG',
      },
    attributes: {
      description:'\'/Jeu de regards\'/: Poster design for the exhibition commemorating the 25th anniversary of Geneva\'/s own publishing house, La Joie de Lire, which took place at the 26 me Salon International du livre et de la presse, in Geneva.'
     },
  },
  {
    name: 'Letter Stamps',
    id: '14',
    type: "grahic",
    year: '2013',
    image: '/CoverPhotos/Galleries/LetterStamps.jpg',
    images: {
      img1: '/LetterStamps/1.jpg',
      img2: '/LetterStamps/2.jpg',
      img3: '/LetterStamps/3.jpg',
      img4: '/LetterStamps/4.jpg',
      img5: '/LetterStamps/5.jpg',
      img6: '/LetterStamps/6.jpg',
      img7: '/LetterStamps/7.jpg',
      img8: '/LetterStamps/8.jpg',
      img9: '/LetterStamps/9.jpg',
      img10: '/LetterStamps/10.jpg',
      img11: '/LetterStamps/11.JPG',
      img12: '/LetterStamps/12.JPG',
      img13: '/LetterStamps/13.JPG',
      img14: '/LetterStamps/14.JPG',
      img15: '/LetterStamps/15.JPG',
      img16: '/LetterStamps/16.jpg',
      img17: '/LetterStamps/17.JPG',
      img18: '/LetterStamps/18.JPG',
      img19: '/LetterStamps/19.JPG',
      img20: '/LetterStamps/20.JPG',
      img21: '/LetterStamps/21.JPG',
      img22: '/LetterStamps/22.JPG',
      img23: '/LetterStamps/23.JPG',
      img24: '/LetterStamps/24.JPG',
      },
    attributes: {
      description:'For a school projet we were asked to make typographic stamps in order to create an alphabet and then design posters with it. The challenge I set myself was to create a stamp that would stand out for its versatility and simplicity. I decided to use rope as the stamp material. For this, I designed a matrix which would work both as a support to the rope as well as a grid for the typeface. It allows for the composition of all the glyphs of the alphabet and 4 different weights (light, regular, medium and bold).'
     },
  },
  {
    name: 'Make A Whish',
    id: '15',
    type: "graphic",
    year: '2018',
    landing: '/CoverPhotos/Lading/MakeAWish.jpg',
    image: '/CoverPhotos/Galleries/MakeAwish.jpg',
    images: {
      img1: '/MakeAWhish/1.jpg',
      img2: '/MakeAWhish/2.jpg',
      img3: '/MakeAWhish/3.jpg',
      },
    attributes: {
      description:'In many cultures around the world, a shooting star is associated with dreams and hope, as it is believed that this phenomenon (a shooting star) has the magical power of granting us a wish. I wanted to play with this idea on my 2018 greeting poster. Therefore, I created an idealistic sky, full of shooting stars, where the main ones are suggesting the numbers 2018 with their movements. A shooting star is also a very ephemeral thing, which echoes with the idea of life itself. The result is a 2018 made out of opportunities, hopes and magic, that has to be fully exploited before vanishing forever. The poster becomes an invitation to dream and reflect on what we would really wish to happen in this new year if we were granted a wish.'   
     },
  },
  {
    name: 'Manifesta',
    id: '16',
    type: "typeface",
    year: '2012',
    landing: '/CoverPhotos/Lading/Manifesta.jpg',
    image: '/CoverPhotos/Galleries/ManifestaV.jpg',
    images: {
      img1: '/Manifesta/1.jpg',
      img2: '/Manifesta/2.jpg',
      img3: '/Manifesta/3.jpg',
      img4: '/Manifesta/4.jpg',
      img5: '/Manifesta/5.jpg',
      img6: '/Manifesta/6.jpg',
      img7: '/Manifesta/7.jpg',
      img8: '/Manifesta/8.jpg',
      img9: '/Manifesta/9.jpg',
      img10: '/Manifesta/10.jpg',
      img11: '/Manifesta/11.JPG',
      img12: '/Manifesta/12.JPG',
      img13: '/Manifesta/13.JPG',
      img14: '/Manifesta/14.JPG',
      img15: '/Manifesta/15.jpg',
      img16: '/Manifesta/Bold.jpg',
      img17: '/Manifesta/Light.jpg',
      img18: '/Manifesta/Regular.jpg',
      img19: '/Manifesta/Vb.jpg',
      },
    attributes: {
      description:'Title or short-text font, influenced both by the geometry-favoring artistic movements of the beginning of the 20th Century and the work of Dutch designer Max Kisman. This fontface aims to explore the relationship between the different parts of the letterforms as well as their hierarchy, while teasing with the limits of legibility. The MANIFESTA font family is formed by four different weights (light, regular, medium, bold), each one with uppercase and lowercase letters, numbers, punctuation marks and diacritic characters.'
     },
  },
  {
    name: 'Mi Mujer',
    id: '17',
    type: "graphic",
    year: '2013',
    landing: '/CoverPhotos/Lading/MiMujer.jpg',
    image: '/CoverPhotos/Galleries/MiMujer.jpg',
    images: {
      img1: '/MiMujer/1.jpg',
      img2: '/MiMujer/2.jpg',
      img3: '/MiMujer/3.jpg',
      img4: '/MiMujer/4.jpg',
      },
    attributes: {
      description:'Poster design inspired by Nicolas Jaar\'s song Mi MujerSchool Project.'   
     },
  },
  {
    name: 'New Year, New Flight',
    id: '18',
    type: "graphic",
    year: '2015',
    landing: '/CoverPhotos/Lading/NewYearNewFlight.jpg',
    image: '/CoverPhotos/Galleries/NewYearNewFight.jpg',
    images: {
      img1: '/NewYearNewFight/1.jpg',
      img2: '/NewYearNewFight/2.jpg',
      img3: '/NewYearNewFight/3.jpg',
      img4: '/NewYearNewFight/4.jpg',
      img5: '/NewYearNewFight/5.jpg',
      },
    attributes: {
      description:'I designed this poster at the end of 2014, just to share my thoughts about the new year 2015, which I knew was going to be a particularly tough one for me. This poster obtained an Honorary Mention at Trnava Poster Triennial International competition 2015.'   
     },
  },
  {
    name: 'Paléo',
    id: '19',
    type: "graphic",
    year: '2013',
    landing: '/CoverPhotos/Lading/Paleo.jpg',
    image: '/CoverPhotos/Galleries/Paleo.jpg',
    images: {
      img1: '/Paleo/1.jpg',
      img2: '/Paleo/2.jpg',
      img3: '/Paleo/3.jpg',
      img4: '/Paleo/4.jpg',
      img5: '/Paleo/5.jpg',
      img6: '/Paleo/BoiteDefinitive-02c.jpg',
      img7: '/Paleo/BoiteDefinitive-all.jpg',
      img8: '/Paleo/Paleo.jpg',
      },
    attributes: {
      description:'Second prize at the Paléo Festival Nyon poster contest. Paléo Festival is today one of Europe\'/s most important musical events.'   
     },
  },
  {
    name: 'Point de Fuite',
    id: '20',
    type: "graphic",
    year: '2012',
    image: '/CoverPhotos/Galleries/PointDeFuite.jpg',
    images: {
      img1: '/Point/1.jpg',
      img2: '/Point/2.jpg',
      img3: '/Point/3.jpg',
      img4: '/Point/4.jpg',
      img5: '/Point/5.jpg',
      img6: '/Point/6.jpg',
      img7: '/Point/7.jpg',
      img8: '/Point/8.jpg',
      img9: '/Point/9.jpg',
      img10: '/Point/10.jpg',
      img11: '/Point/11.JPG',
      img12: '/Point/12.JPG',
      img13: '/Point/13.JPG',
      img14: '/Point/14.JPG',
      img15: '/Point/15.jpg',
      img16: '/Point/16.jpg',
      img17: '/Point/17.jpg',
      img18: '/Point/18.jpg',
      img19: '/Point/19.JPG',
      img20: '/Point/20.jpg',
      img21: '/Point/21.jpg',
      img22: '/Point/22.jpg',
      img23: '/Point/23.jpg',
      img24: '/Point/24.jpg',
      img25: '/Point/25.jpg',
      },
    attributes: {
      description:'Conception and mounting of the exhibition \'/Point de Fuite\'/, which presented artist Isabelle Pralong\'/s career retrospective and took place in Geneva\'/s Biblioth�que de la Cit� from Dec 9th, 2011 to Jan 31st, 2012. Done in collaboration with Tammara Leites, Alexia Segura, Pierre Schilling et Antoine Schmitt, as an assignment for Sandrine Pelletier\'/s scenography course at HEAD - Geneve.'
     },
  },
  {
    name: 'La Dame De La Mer',
    id: '21',
    type: "grahic",
    year: '2014',
    landing: '/CoverPhotos/Lading/DameDeLaMer.jpg',
    image: '/CoverPhotos/Galleries/LaDameDeLaMere.jpg',
    images: {
      img1: '/LaDamedeLaMer/1.jpg',
      img2: '/LaDamedeLaMer/2.jpg',
      img3: '/LaDamedeLaMer/3.jpg',
      img4: '/LaDamedeLaMer/4.jpg',
      img5: '/LaDamedeLaMer/5.jpg',
      img6: '/LaDamedeLaMer/6.jpg',
      img7: '/LaDamedeLaMer/7.jpg',
      img8: '/LaDamedeLaMer/8.jpg',
      img9: '/LaDamedeLaMer/9.jpg',
      img10: '/LaDamedeLaMer/10.jpg',
      img11: '/LaDamedeLaMer/11.JPG',
      img12: '/LaDamedeLaMer/12.JPG',
      img13: '/LaDamedeLaMer/13.JPG',
      img14: '/LaDamedeLaMer/14.JPG',
      img15: '/LaDamedeLaMer/15.JPG',
      },
    attributes: {
      description:'For a school photography project, in collaboration with the Carouge Theatre and the Fusterie exhibition space, we were asked to reinterpret the play �The lady from the sea� written by Henrik Ibsen. As a joint project with eleven other students, our work was exhibited at the Fusterie church in Geneva, as part of an audio-visual installation. My work deals with an everyday life overtaken by fear and anguish provoked by ghosts of a past love. Past and present blend, memories and reality confuse and collide and dreams becomes real.'
     },
  },
  {
    name: 'Post Tenebras Rock',
    id: '22',
    type: "graphic",
    year: '2012',
    image: '/CoverPhotos/Galleries/PostTenebrasRock.jpg',
    images: {
      img1: '/PostTenebrasRock/1.jpg',
      img2: '/PostTenebrasRock/2.jpg',
      img3: '/PostTenebrasRock/3.jpg',
      img4: '/PostTenebrasRock/4.jpg',
      img5: '/PostTenebrasRock/5.jpg',
      img6: '/PostTenebrasRock/6.jpg',
      img7: '/PostTenebrasRock/7.jpg',
    },
    attributes: {
      description:'Posters & flyers proposition for Post Tenebras Rock (2011) concerts at l\'/Usine, Geneva'
     },
  },
  {
    name: 'Thesaurus',
    id: '22',
    type: "typeface",
    year: '2017',
    landing: '/CoverPhotos/Lading/Thesaurus.jpg',
    image: '/CoverPhotos/Galleries/Thesaurus.jpg',
    images: {
      img1: '/Thesaurus/1.jpg',
      img2: '/Thesaurus/2.jpg',
      img3: '/Thesaurus/3.jpg',
      img4: '/Thesaurus/4.jpg',
      img5: '/Thesaurus/5.jpg',
      img6: '/Thesaurus/6.jpg',
      img7: '/Thesaurus/7.jpg',
      img9: '/Thesaurus/9.jpg',
      img10: '/Thesaurus/10.jpg',
      img11: '/Thesaurus/11.JPG',
      img12: '/Thesaurus/12.JPG',
      img13: '/Thesaurus/13.JPG',
      img14: '/Thesaurus/14.JPG',
      img15: '/Thesaurus/15.jpg',
      img16: '/Thesaurus/16.jpg',
      img17: '/Thesaurus/17.jpg',
      img18: '/Thesaurus/18.jpg',
      img19: '/Thesaurus/19.JPG',
      img20: '/Thesaurus/20.jpg',
      img21: '/Thesaurus/21.jpg',
      img22: '/Thesaurus/22.jpg',
      img23: '/Thesaurus/23.jpg',
      img24: '/Thesaurus/24.jpg',
      img25: '/Thesaurus/25.jpg',
      img26: '/Thesaurus/26.jpg',
      img27: '/Thesaurus/27.jpg',
      img28: '/Thesaurus/28.jpg',
      img29: '/Thesaurus/29.jpg',
      img30: '/Thesaurus/30.jpg',
    },
    attributes: {
      description:'Thesaurus is a typeface inspired by the typographic history of the city of Geneva. Thesaurus is based on the types that Robert Estienne brought from Paris to Geneva, which were later used by his son, Henri II Estienne, for printing the famous book Thesaurus Graecae Linguae. These metal types served, in some way, as a bridge between France and Switzerland, between Catholicism and Protestantism, and now, through Thesaurus, between past and present. Thesaurus was released by Typotheque. Below, some pictures from Thesaurus\'/ Specimen, which I have designed for Typothque. Thesaurus has received the Gold award (first prize) at the European Design Awards 2018 and the the Gold Award & Best Project of Category at the LAD - Latin American Design Awards 2019. Furthermore, it was one of the 4 projects awarded with the Mention of Excellence at the 8th Latin-American typedesign biennial by Tipos Latinos, 2018 - out of 444 projects submitted this year. Thesaurus was selected in the Superfamily category. It has also been awarded with "Gold" in the Graphis Type 4: Typeface Design Competition.'
     },
  },
  {
    name: 'Tijuana Panthers',
    id: '23',
    type: "graphic",
    year: '2014',
    landing: '/CoverPhotos/Lading/TijuanaPanthers.jpg',
    image: '/CoverPhotos/Galleries/TijuanaPanthers.jpg',
    images: {
      img1: '/TijuanaPanthers/1.jpg',
      img2: '/TijuanaPanthers/2.jpg',
      img3: '/TijuanaPanthers/3.jpg',
      img4: '/TijuanaPanthers/4.jpg',
      img5: '/TijuanaPanthers/5.jpg',
    },
    attributes: {
      description:'I was asked by Rock This Town (association which organises concerts in Geneva) to design a poster to promote the concert of Californian band Tijuana Panthers.'
     },
  },
  {
    name: 'Time Out',
    id: '24',
    type: "graphic",
    year: '2013',
    landing: '/CoverPhotos/Lading/TimeOut.jpg',
    image: '/CoverPhotos/Galleries/TimeOut.jpg',
    images: {
      img1: '/TimeOut/1.jpg',
      img2: '/TimeOut/2.jpg',
      img3: '/TimeOut/3.jpg',
      img4: '/TimeOut/4.jpg',
      img5: '/TimeOut/5.jpg',
    },
    attributes: {
      description:'The New York magazine TimeOut asked me to design the cover for his spring preview issue (late February, 2013), and wanted me to reinvent my Beyond the Box poster. For me, spring is aboout flowers, paper windmills and kaleidoscopes, so my visual concept was inspired by this mood.'
     },
  },
  {
    name: 'Tomorrow',
    id: '25',
    type: "graphic",
    year: '2013',
    landing: '/CoverPhotos/Lading/Tomorrow.jpg',
    image: '/CoverPhotos/Galleries/Tomorrow.jpg',
    images: {
      img1: '/Tomorrow/1.jpg',
      img2: '/Tomorrow/2.jpg',
      img3: '/Tomorrow/3.jpg',
      img4: '/Tomorrow/4.jpg',
      img5: '/Tomorrow/5.jpg',
    },
    attributes: {
      description:'The poster flirts with the concepts of luck and randomness, which are strongly related to the idea of future (tomorrow), since no matter how much effort we put into it, things might not turn out the way we\'/d planned.'
     },
  },
  {
    name: 'Typography Heroes',
    id: '26',
    type: "typeface",
    year: '2013',
    landing: '/CoverPhotos/Lading/TypographyH.jpg',
    image: '/CoverPhotos/Galleries/TypographicHeroes.jpg',
    images: {
      img1: '/TypographyHeroes/1.jpg',
      img2: '/TypographyHeroes/2.jpg',
      img3: '/TypographyHeroes/3.jpg',
      img4: '/TypographyHeroes/4.jpg',
      img5: '/TypographyHeroes/5.jpg',
      img6: '/TypographyHeroes/6.jpg',
      img7: '/TypographyHeroes/7.jpg',
      img9: '/TypographyHeroes/9.jpg',
      img10: '/TypographyHeroes/10.jpg',
      img11: '/TypographyHeroes/11.JPG',
      img12: '/TypographyHeroes/12.JPG',
      img13: '/TypographyHeroes/13.JPG',
      img14: '/TypographyHeroes/14.JPG',
      img15: '/TypographyHeroes/15.jpg',
      img16: '/TypographyHeroes/16.jpg',
      img17: '/TypographyHeroes/17.jpg',
      img18: '/TypographyHeroes/18.jpg',
      img19: '/TypographyHeroes/19.JPG',
      img20: '/TypographyHeroes/20.jpg',
      img21: '/TypographyHeroes/21.jpg',
      img22: '/TypographyHeroes/22.jpg',
      img23: '/TypographyHeroes/23.jpg',
      img24: '/TypographyHeroes/24.jpg',
      img25: '/TypographyHeroes/25.jpg',
      img26: '/TypographyHeroes/26.jpg',
      img27: '/TypographyHeroes/27.jpg',
      img28: '/TypographyHeroes/28.jpg',
      img29: '/TypographyHeroes/29.jpg',
      img30: '/TypographyHeroes/30.jpg',
      img31: '/TypographyHeroes/31.jpg',
      img32: '/TypographyHeroes/32.jpg',
      img33: '/TypographyHeroes/33.jpg',
    },
    attributes: {
      description:'My concept was to combine two printing techniques; One of the latest: the Risograph (RISO), with one of the oldest printing methods: movable type page setting and press printing. First of all, the portrait images were printed with the RISO. Then, all the texts were composed by hand printing over the portraits using a press. I chose these 4 designers taking in consideration several aspects: the impact their typefaces had in the world of typography and the availability of the metal characters at school. I also picked these 4 designers because they all lived in a different period of time. Therefore they faced different problems. Their work somehow represents the evolution in typography This is a school project in progress, the two other posters will be up soon.'
     },
  },
  {
    name: 'Viga',
    id: '27',
    type: "typeface",
    year: '2011',
    image: '/CoverPhotos/Galleries/Viga.jpg',
    images: {
      img1: '/Viga/1.jpg',
      img2: '/Viga/2.jpg',
      img3: '/Viga/3.jpg',
      img4: '/Viga/4.jpg',
      img5: '/Viga/5.jpg',
      img6: '/Viga/6.jpg',
      img7: '/Viga/7.jpg',
      img8: '/Viga/8.jpg',
    },
    attributes: {
      description:'VIGA is an experimental capitals-only display font influenced by constructivism, with a high level of abstraction. The grid I created for developing VIGA was inspired by metal joists used in architecture.'
     },
  },
  {
    name: 'Welftormat',
    id: '28',
    type: "graphic",
    year: '2011',
    landing: '/CoverPhotos/Lading/Weltformat.jpg',
    image: '/CoverPhotos/Galleries/Weltformat.jpg',
    images: {
      img1: '/Welftormat/1.jpg',
      img2: '/Welftormat/2.jpg',
      img3: '/Welftormat/3.jpg',
      img4: '/Welftormat/4.jpg',
      img5: '/Welftormat/5.jpg',
    },
    attributes: {
      description:'Finalist in the students\'/ international contest of the Weltformat 2011 poster festival at Lucerne - Switzerland, this poster was chosen between more than 400 students of 20 different countries as a response to the theme: poster for the poster.'
     },
  },
  {
    name: 'Brick',
    id: '28',
    type: "typeface",
    year: '2019',
    landing: '/CoverPhotos/Lading/BrickTypefamily.jpg',
    image: '/CoverPhotos/Galleries/BrickTypefamilyLandscape.jpg',
    attributes: {
      description:'Brick'
     },
  },
]
 
export default projects;
